# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0ba1d468b8eab495c81358c75638f1f186c6824a5ec180de9f896bea9b84d06888a7aaf50317977448c621a2609e2b358eb63620ec63f4e3ed9830826f26228

test:
  secret_key_base: a31d75c281d9593734d38820779356f2ce90297ecf35f75c78e8fc835d0d18ca69ac373512f005cd90ef97028d8c61c9753ce56555c43f21473c43f7e4d2cab5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
